### ISSUE TITLE
Error when clicked suggested

### ISSUE THREAD

**Issue by Mystik01** [spikespaz/search-deflector#91] opened 2020-09-17 17:02 UTC
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://www.bing.com/search?q=Bing+Halloween+quiz&setlang=en-gb&mkt=en-gb&form=M50025&OCID=M50025
```

## How to Reproduce
![image](https://user-images.githubusercontent.com/65687597/93503396-eb8e0400-f90f-11ea-962c-8c82b1f5c984.png)

**Query string:**
```
SEE IMAGE

```

**Query or URL:**
```
SEE IMAGE
![image](https://user-images.githubusercontent.com/65687597/93503419-f3e63f00-f90f-11ea-9a75-c09feac8f856.png)


```

**Steps to reproduce the behavior:**

1. Go to 'windows start'
2. Click on 'suggested'

## Environmental Details

**Browser**: Opera GX Stable

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
C:\Users\mystik\AppData\Local\Programs\Opera GX\Launcher.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Pro` |
| Insiders Preview |  |

**Comment by spikespaz** [comment] 2020-09-29 06:37
Duplicate of #81. This is fixed by 49e833f. The changes will be available in the new version.

**Closed as completed by spikespaz** 2020-09-29 06:37 UTC
Labels: bug, duplicate
