### ISSUE TITLE
Launching error

### ISSUE THREAD

**Issue by Kumaursa** [spikespaz/search-deflector#30] opened 2018-09-27 12:36 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": File not found. (error 2)
```

**Stack Trace:**
```
0x00425ECF
0x00425C82
0x0041ED5D

```

**Comment by spikespaz** [comment] 2018-09-27 13:42
Duplicate of #8.

**Closed by spikespaz** 2018-09-27 13:42 UTC
Labels: bug, duplicate
