### ISSUE TITLE
install issue: configuration crash w/ 32bit Windows

### ISSUE THREAD

**Issue by Evan-Galvin** [spikespaz/search-deflector#28] opened 2018-09-21 12:00 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x000D5ECF
0x000D5C82
0x000CED5D

```

**Comment by Evan-Galvin** [comment] 2018-09-21 12:02
sorry i did not submit this sooner

**Comment by spikespaz** [comment] 2018-09-21 12:05
This is what I was afraid of. Another duplicate of #8, still unresolved. Perhaps you wouldn't mind reading through the comments of that issue? Let me know if your nephew's system meets any of that criteria.

**Closed by spikespaz** 2018-09-21 12:05 UTC
