### ISSUE TITLE
Simply is nonfunctional

### ISSUE THREAD

**Issue by MulverineX** [spikespaz/search-deflector#6] opened 2018-08-27 01:37 UTC
I followed the installation steps to a T, selected chrome and google, and when I clicked a web link in the start menu for the first time, I set launcher.exe for always

However, the link did not open up, it did simply nothing, no clue as to why.

**Comment by MulverineX** [comment] 2018-08-27 02:42
You shouldn't have to use that..., anyway, when I set it to that, manually typing something works, but if you tell cortana to "search the web for (blank)" nothing happens. If I tell cortana "show me pictures of cats", and click the see more on bing button, nothing happens

**Comment by Freyam** [comment] 2018-08-27 03:10
i only use Cortana to search by typing.....wait for the dev to reply

**Comment by spikespaz** [comment] 2018-08-27 04:41
Duplicate of #5.

This issue has been fixed as of d138f5e, it was an issue with Chromium not liking a new environment when the process was spawned.

There was also a bug most probably didn't notice where Firefox would open without your extensions if it wasn't already open prior to searching.

Open your Start Menu, scroll down the programs list on the side, expand the "Search Deflector" folder, and click "Force Update". Accept the UAC prompt, wait a few seconds while it downloads in the background, and try searching again.

You shouldn't need to run the setup again, but it's worth a try if this doesn't fix it. If this isn't fixed, come back and tell me.

Or, manually download the latest [release](https://github.com/spikespaz/search-deflector/releases/tag/0.1.4).

**Closed by spikespaz** 2018-08-27 04:41 UTC
