### ISSUE TITLE
Can't install search deflector on win 10 pro 17741.rs5-release.180814-1430

### ISSUE THREAD

**Issue by lordvlad** [spikespaz/search-deflector#14] opened 2018-08-28 17:32 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x00007FF684E9EEED
0x00007FF684E9EC46
0x00007FF684E97AFC
0x00007FF684E8459C
0x00007FF684E398BA
0x00007FF684E3B708
0x00007FF684E27076
0x00007FF684E3C4F2
0x00007FF684E3C456
0x00007FF684E25C32
0x00007FF684E25AD0
0x00007FF684E8ABAD
0x00007FF684E8AA5A
0x00007FF684EA9478
0x00007FFF46FD87E4 in BaseThreadInitThunk
0x00007FFF491FB2B1 in RtlUserThreadStart

```

**Comment by spikespaz** [comment] 2018-08-28 18:12
Duplicate of #8. Please watch that issue for updates and discussion. Also, please read the existing conversation in that issue and add your feedback, the more I understand the commonalities between your environments the easier I can fix this because I can't reproduce the issue.

**Closed by spikespaz** 2018-08-28 18:12 UTC
Labels: bug, duplicate
