### ISSUE TITLE
Invalid Issue

### ISSUE THREAD

**Issue by Candybar121** [spikespaz/search-deflector#87] opened 2020-09-02 23:56 UTC
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://www.bing.com/search?q=power%20mode%20windows%2010%20site:microsoft.com&form=B00032&ocid=SettingsHAQ-BingIA&mkt=en-US
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

## Environmental Details

**Browser**: Google Chrome

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Core` |
| Insiders Preview |  |

**Comment by spikespaz** [comment] 2020-09-29 06:38
Duplicate of #81. This is fixed by 49e833f. The changes will be available in the new version.

**Closed as completed by spikespaz** 2020-09-29 06:38 UTC
Labels: bug, duplicate, invalid
