### ISSUE TITLE
Search Deflector Failed

### ISSUE THREAD

**Issue by prakharb5** [spikespaz/search-deflector#89] opened 2020-09-06 10:00 UTC
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://go.microsoft.com/fwlink/?LinkId=517009
```

## How to Reproduce

**Steps to reproduce the behavior:**

Choose "How does it work?" in DEP settings in performance options window.

## Expected Behavior

Browser should have opened

## Environmental Details

**Browser**: Brave Nightly

**Search Engine:** DuckDuckGo

| Windows Version | `2009` |
| --- | --- |
| Build Number | `19042` |
| Edition | `Core` |
| Insiders Preview | Yes  |

Screenshot - 

![image](https://user-images.githubusercontent.com/51435948/92323401-10ec5980-f056-11ea-88e7-4e1c9c5d1268.png)

**Comment by spikespaz** [comment] 2020-09-29 06:38
Duplicate of #81. This is fixed by 49e833f. The changes will be available in the new version.

**Closed as completed by spikespaz** 2020-09-29 06:38 UTC
Labels: bug, duplicate
