### ISSUE TITLE
Windows 11 - Default app

### ISSUE THREAD

**Issue by Baaasty** [spikespaz/search-deflector#245] opened 2022-02-07 18:21 UTC
![Screenshot_1](https://user-images.githubusercontent.com/46427883/152848259-f8f959b6-76dc-45d8-b1b1-bc2c27f42f48.png)

Can't find it....

**Comment by zyxtheros** [comment] 2022-02-16 22:08
Same issue in WIndows version 21H2 as of 2/16/22. Changed default browser to google chrome in the apps menu but windows search still directing to bing

**Comment by spikespaz** [comment] 2022-02-16 22:33
Duplicate of #238

**Closed as completed by spikespaz** 2022-02-16 22:33 UTC
Labels: bug, duplicate
