### ISSUE TITLE
I paid for this utility and this is what I get "Search Deflector failed launch" error .

### ISSUE THREAD

**Issue by Wisoooo** [spikespaz/search-deflector#94] opened 2020-10-03 14:28 UTC
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**

```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

## Environmental Details

**Browser**: 

**Search Engine:** 

**Custom browser path:**
```

```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Enterprise` |
| Insiders Preview |  |

**Comment by AlSmithAU** [comment] 2020-10-05 04:16
I installed Search Deflector successfully on two machines today, the third failed. Most importantly I think the difference is that the user did not have admistrative rights. When I started the install I got a privlige escallation prompt and signed in with an account with admin rights to complete the install, all seemed to go fine but every search results in an error 2, cannot find the reg key.

Checked in the registry and the SearchDeflector key is not present in HKEY_CURRENT_USER\SOFTWARE\Clients.

![](https://lh3.googleusercontent.com/-oYSbj_PauPw/X3qZZWOfL9I/AAAAAAAAAaA/gt385mSFXhgbahzKo70NtZTfVpmGOg_1QCK8BGAsYHg/s0/2020-10-04.png)

**Comment by AlSmithAU** [comment] 2020-10-05 04:45
Update, SearchDeflector is present in HKEY_CURRENT_USER\SOFTWARE\Clients for that admin account that authorised the installation. As part of the first install I did check the all users check box, when I got the error I re-ran the install without the all users check box but it made no difference.

I exported the SearchDeflector key from the admin user and imported it to the end user's Software\Clients registry and it is now working fine.

Great software by the way!

**Comment by Wisoooo** [comment] 2020-10-05 15:01
I just ran the compatibility mode features in Windows 10 and when it fails
I choose (compatibility mode second choice) "run with administrative
privileges" and then it works.

**Comment by spikespaz** [comment] 2020-10-17 01:10
Looks like you two already found that the program needs to be installed with admin privileges. I'm going to close the issue since it seems like the issue is resolved. Let me know if you need any more help.

I just wanted to also use this to make a statement, I appreciate the detail and effort put into @AlSmithAU's response to OP, but OP, if I had noticed this issue before the activity started I would have marked this issue invalid and closed it without saying a word. There is no detail, the issue is not described, and the placeholder text isn't even replaced or removed. Lazy bug reports receive lazy/no responses.

Also, activity on the project has slowed because I need money. This project doesn't make enough money, so I'm working customer service every day all the time and I don't have any time left. Sorry you guys are paying for something that has slowed down so much but I just can't keep up. When I have a minute to breathe I will finish the next release, there are a few staged features and bug fixes that I haven't had the chance to polish and deploy.

**Closed as completed by spikespaz** 2020-10-17 01:10 UTC
Labels: bug
