### ISSUE TITLE
32bit test remains same results

### ISSUE THREAD

**Issue by Evan-Galvin** [spikespaz/search-deflector#31] opened 2018-09-29 19:38 UTC
this is when using the test.exe you emailed me.  version number in terminal(top left corner) still said 0.2.2-master just in case that was in fact the same version as previous attempts

I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x013F5BAF
0x013F5962
0x013EEA3D

```

**Comment by spikespaz** [comment] 2018-09-30 00:01
It wasn't. It was a development build, I just didn't change the branch or version number because that would list a new release on GitHub.

I'm going to close this again because it's still a duplicate of #8.

I appreciate the assistance.

**Closed** 2018-09-30 00:01 UTC
