### ISSUE TITLE
Doesnt Open in a New Chrome windows....

### ISSUE THREAD

**Issue by Freyam** [spikespaz/search-deflector#7] opened 2018-08-27 02:16 UTC
after i click enter after typing out the search in the windows start menu, it doesnt tske me anywhere...
on the first time, they asked me to choose the default way to handle this (the oprions wer : launcher or edge)
i thought laucnher must be yours, so i chose that...but now it doesnt take me anywhere....

EDIT: It works.....i changed it to System Default and now it works.....but it still shows the output at the time of typing as bing...can i do something about that too??

**Comment by spikespaz** [comment] 2018-08-27 04:42
Duplicate of #5.

This issue has been fixed as of d138f5e, it was an issue with Chromium not liking a new environment when the process was spawned.

There was also a bug most probably didn't notice where Firefox would open without your extensions if it wasn't already open prior to searching.

Open your Start Menu, scroll down the programs list on the side, expand the "Search Deflector" folder, and click "Force Update". Accept the UAC prompt, wait a few seconds while it downloads in the background, and try searching again.

You shouldn't need to run the setup again, but it's worth a try if this doesn't fix it. If this isn't fixed, come back and tell me.

Or, manually download the latest [release](https://github.com/spikespaz/search-deflector/releases/tag/0.1.4).

**Closed by spikespaz** 2018-08-27 04:42 UTC

**Comment by spikespaz** [comment] 2018-08-27 04:43
> EDIT: It works.....i changed it to System Default and now it works.....but it still shows the output at the time of typing as bing...can i do something about that too??

Also, what do you mean by "output"? Is a black console window opening and then closing quickly?

**Comment by Freyam** [comment] 2018-08-27 05:39
output in the sense the right side while u type anything in the search box
![screenshot 2](https://user-images.githubusercontent.com/35898769/44642394-0580e500-a9dd-11e8-9fd4-dfe8ed9f16c9.png)
the bing thing.....can i change that to Google

**Comment by Freyam** [comment] 2018-08-27 05:43
EDIT: after running the FORCE UPDATE, it no longer opens chrome......

**Comment by spikespaz** [comment] 2018-08-27 06:01
It broke worse? Try a fresh install. Uninstall the program and download the latest manually.

Also, search results in the start menu will always show as Bing unfortunately. There is no way to change that because it's built into Windows.

**Comment by Freyam** [comment] 2018-08-27 06:11
Its back to normal....
Thanks a ton.....Keep it up......

**Comment by spikespaz** [comment] 2018-09-06 23:04
Hey @Freyam woold you consider starring the repo since this issue has been fixed?
