### ISSUE TITLE
Registry Setup Error

### ISSUE THREAD

**Issue by leelings** [spikespaz/search-deflector#27] opened 2018-09-21 09:30 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x011D5ECF
0x011D5C82
0x011CED5D

```

**Comment by spikespaz** [comment] 2018-09-21 09:34
Please put a little more effort into bug reports. Don't just title it "error" and expect me to understand what happened. What were you doing when this error occurred? Was it in the setup command prompt?

**Comment by spikespaz** [comment] 2018-09-21 10:09
Duplicate of #8. Please add any additional information as a comment in that issue, and watch it for updates.

**Closed by spikespaz** 2018-09-21 10:09 UTC
Labels: bug, duplicate
