### ISSUE TITLE
press F1 will open windows defalt help and return error (open edge and search bing)

### ISSUE THREAD

**Issue by ilcpm** [spikespaz/search-deflector#92] opened 2020-09-18 09:03 UTC
> **IMPORTANT:** READ EVERYTHING!!! That includes the wiki. Make sure you've skimmed the wiki before making a bug report.
> https://github.com/spikespaz/search-deflector/wiki
>
> This issue should be properly formatted in markdown. If you don't know what that is, read the following website before continuing:
> https://guides.github.com/features/mastering-markdown/
>
> Most of the text in this issue should be replaced with your own or deleted. Do not delete section headers unless the information they would contain is irrelevant or inapplicable.

## Bug Description

If you have any other details, replace this line, otherwise delete it.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://go.microsoft.com/fwlink/?LinkId=517009
```

## How to Reproduce

**when pressing `F1` in explorer or other windows which will `open edge and search bing for windows help`, this program will report the error.**

## Environmental Details

**Browser**: Google Chrome

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
D:\Program Files\Chrome\MyChrome.exe
```

**Custom search engine URL:**
```
baidu.com/s?wd={{query}}
```

| Windows Version | `2004` |
| --- | --- |
| Build Number | `19041` |
| Edition | `Enterprise` |
| Insiders Preview |  |

**Comment by spikespaz** [comment] 2020-09-29 06:36
Duplicate of #81. This is fixed by 49e833f. The changes will be available in the new version.

**Closed as completed by spikespaz** 2020-09-29 06:36 UTC
Labels: bug, duplicate
