### ISSUE TITLE
Crashed after setup.

### ISSUE THREAD

**Issue by Phoenixthedoggo** [spikespaz/search-deflector#22] opened 2018-09-06 22:32 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x00007FF78261151D
0x00007FF782611276
0x00007FF78260A12C
0x00007FF7825F6BCC
0x00007FF7825A9F9A
0x00007FF7825ABDE8
0x00007FF782597616
0x00007FF7825ACBD2
0x00007FF7825ACB36
0x00007FF782595F98
0x00007FF782595E10
0x00007FF7825FD1DD
0x00007FF7825FD08A
0x00007FF78261BAA8
0x00007FFC952A3034 in BaseThreadInitThunk
0x00007FFC958F1431 in RtlUserThreadStart

```

**Comment by spikespaz** [comment] 2018-09-06 23:01
Duplicate of #8.

**Closed by spikespaz** 2018-09-06 23:01 UTC
