### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by fernandex00** [spikespaz/search-deflector#9] opened 2018-08-27 03:40 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x00007FF7B1ACF0CD
0x00007FF7B1ACEE26
0x00007FF7B1AC7CDC
0x00007FF7B1AB477C
0x00007FF7B1A698BA
0x00007FF7B1A6B708
0x00007FF7B1A57076
0x00007FF7B1A6C4F2
0x00007FF7B1A6C456
0x00007FF7B1A55C32
0x00007FF7B1A55AD0
0x00007FF7B1ABAD8D
0x00007FF7B1ABAC3A
0x00007FF7B1AD9658
0x00007FFC87373034 in BaseThreadInitThunk
0x00007FFC89461431 in RtlUserThreadStart

```

**Comment by spikespaz** [comment] 2018-08-27 04:49
Duplicate of #8. Please watch that issue for updates and discussion.

**Closed by spikespaz** 2018-08-27 04:49 UTC
Labels: bug, duplicate

**Comment by shalvah** [comment] 2018-08-27 07:56
Experiencing the same issue
