### ISSUE TITLE
Search Deflector launch failed

### ISSUE THREAD

**Issue by trongtunguyen08** [spikespaz/search-deflector#35] opened 2018-10-08 14:15 UTC
I have encountered an error launching Search Deflector.
The error information follows below.

**File:** `std\windows\registry.d`

**Line:** 495

**Message:**
```
Value cannot be opened: "": The system cannot find the file specified. (error 2)
```

**Stack Trace:**
```
0x00085ECF
0x00085C82
0x0007ED5D

```

**Comment by spikespaz** [comment] 2018-10-08 14:50
Duplicate of #8.

**Closed** 2018-10-08 14:50 UTC
Labels: bug, duplicate
