### ISSUE TITLE
Help links in the Settings panel return error and fail.

### ISSUE THREAD

**Issue by mrBrain101** [spikespaz/search-deflector#83] opened 2020-08-08 10:01 UTC
## Bug Description

Help links in the Settings panel return error and fail.

**File:** `source\deflector.d`

**Line:** 53

**Message:**

```
There was an error deflecting your search. Passed URI is:	microsoft-edge:https://go.microsoft.com/fwlink/p/?linkid=827594
```

## How to Reproduce

**Query string:**
```

```

**Query or URL:**
```

```

**Steps to reproduce the behavior:**

1. Go to 'Settings' panel
2. Click on 'Sytem'
3. Scroll down to 'Have a question?'
3. Click on 'Setting up multiple monitors'

## Expected Behavior

Google Chrome opens the help link from Settings panel

## Environmental Details

**Browser**: Google Chrome

**Search Engine:** UNKNOWN STRING

**Custom browser path:**
```
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe
```

**Custom search engine URL:**
```
google.com/search?q={{query}}
```

| Windows Version | `1909` |
| --- | --- |
| Build Number | `18363` |
| Edition | `Core` |
| Insiders Preview |  |

**Comment by spikespaz** [comment] 2020-08-13 16:56
Duplicate of #81.

**Closed as completed** 2020-08-13 16:56 UTC
Labels: bug, duplicate
